### ISSUE TITLE
`depends_on` needs `when` logic

### ISSUE THREAD

**Issue by mathstuf** [scalability-llnl/spack#125]
Basically, ParaView has about a dozen meaningful flags that can be twiddled for how it gets built. The dependencies that are required depend on these flags, but there seems to be no way to express it. I could add them all as unconditional depedencies, but it seems excessive to require Python, MPI, Qt, and more if all you want is to work with a C++ Catalyst interface.

**Comment by tgamblin** [comment]
This is implemented in `develop`: https://github.com/scalability-llnl/spack/wiki/Telcon%3A-2015-05-14

Sorry it's not documented yet!
