### ISSUE TITLE
Using dotkit on non-LC machine

### ISSUE THREAD

**Issue by justintoo** [scalability-llnl/spack#13]
@tgamblin Is it straightforward to install Dotkit on a non-LC machine? I need this on my desktop system in order to utilize `spack use` and/or `spack load`. Or is there an alternative method of sourcing the tools in the absence of dotkit?

**Comment by tgamblin** [comment]
TCL modules would also work and might be available outside LLNL. There is also lmod, probably the best one out there right now. It's from folks at TACC. You'd need to add support for it though -- slightly different lua syntax



Sent with Good (www.good.com)


-----Original Message-----

**Comment by tgamblin** [comment]
@justintoo: I'm going to close this one for now, but I made an issue in JIRA to get some sort of modules package working so that shell support will work without dependencies.

**Comment by tgamblin** [comment]
@justintoo See here: https://lc.llnl.gov/jira/browse/SPACK-54
