### ISSUE TITLE
URL for xz package is broken

### ISSUE THREAD

**Issue by PaulDapolito** [scalability-llnl/spack#138]
When trying to install the xz package, we see an error that indicates that the URL for the package is broken:
```
==> Installing xz
==> Trying to fetch from http://tukaani.org/xz/xz-5.2.0.tar.bz2

curl: (22) The requested URL returned error: 403 Forbidden
==> Fetching from http://tukaani.org/xz/xz-5.2.0.tar.bz2 failed.
==> Error: All fetchers failed for xz-5.2.0-qhllisblbadybmawb3sbs6xwby4vgeyz
```

**Comment by davidbeckingsale** [comment]
This isn't a bug. From the xz websiite:
> Availability of .tar.gz and .tar.bz2 files of certain old XZ Utils versions have been temporary suspended because they are consume too much of the web hosting bandwidth quota. The files will be restored in November 2015, but further changes may be needed if the problem persist. Sorry for the inconvenience.

**Comment by tgamblin** [comment]
I think the solution would be to update the URL.  There is an ongoing problem of old packages going down, though -- should probably think about providing some kind of sanctioned mirror to address this.

**Comment by PaulDapolito** [comment]
We found a usable link here: http://tukaani.org/xz/xz-5.2.2.tar.bz2

**Comment by tgamblin** [comment]
@PaulDapolito: Can you add that to the package as a new version, then submit a pull request?  There should be no need to delete the old one, but having the newer one will make it the default.

**Comment by PaulDapolito** [comment]
Sure, that sounds good!

**Comment by mathstuf** [comment]
Or a mirror could be used. Not sure of the best place to put it though.

**Comment by tgamblin** [comment]
Closed for now but I agree that a mirror is the right long-term solution
