### ISSUE TITLE
"linker was not configured to use sysroots"

### ISSUE THREAD

**Issue by eschnett** [scalability-llnl/spack#177]
I want to install `gcc` on Ubuntu 14.04. `gcc`'s dependencies installed fine, but `gcc` itself doesn't build. I see this error message that I don't understand. Have you seen it before, or can you give me a pointer?

The system has gcc 4.9.2 installed; I am trying to install gcc 5.2 via Spack. This looks as if it was using Spack's `binutils` package.

Google didn't find any good answers. Apart from "don't mess with your system", there is one message suggesting to build `ld` with the `--with-sysroot` option. However, `--with-sysroot` expects a path as argument, and it's unclear to me what argument that could be. I also don't understand what Spack is trying to achieve by using the `--sysroot` argument.

```
configure:4370: checking for C compiler default output file name
configure:4392: /xfs1/eschnetter/src/spack/lib/spack/env/cc    conftest.c  >&5 /xfs1/eschnetter/src/spack/opt/spack/linux-x86_64/gcc-4.9.2/binutils-2.25-gqbrzkvzz2q236u5tkyo7uxn2u5i5b4q/bin/ld: this linker was not configured to use sysroots
collect2: error: ld returned 1 exit status
```

**Comment by alalazo** [comment]
@tgamblin , @mplegendre : I think the issue stems from the configuration of system `gcc` in Ubuntu, which has `--with-sysroot=/`
```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.3-8ubuntu2~14.04' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.3 (Ubuntu 4.9.3-8ubuntu2~14.04) 
```
I'll try to see if I can find a way to employ the default linker for whatever compiler we are using in stage 1. Does it seem reasonable to you?

**Comment by tgamblin** [comment]
I was able to reproduce this via travis: https://travis-ci.org/tgamblin/spack/builds/95503933, even after @mplegendre's #203 (not surprising but I thought I'd try).  

I need to get an Ubuntu VM set up on my machine to really try it out.  Ubuntu seems to fail in weird ways that RHEL does not.

@alalazo: I'm not sure this has to do with the system linker, but I could be wrong.  Because `gcc` depends on `binutils`, `ld` from `binutils` in in the `PATH` when the build happens, and it seems to me that the error could be coming from something wrong with the `binutils` build.  If you want to take a stab at this while I'm getting set up, be my guest.

**Comment by alalazo** [comment]
@tgamblin: I am quite sure it's the `binutils` build. In fact, it seems that having a system compiler configured with `--with-sysroot=/` creates an incompatibility when using a `binutils` that was not configured the same.

**Comment by alalazo** [comment]
@tgamblin, @mplegendre : Can you check if my branch above doesn't break any build on your machines? I tried building gcc@5.2.0 on a RHLE 6 and on Ubuntu 14.04 and they worked fine for me.

**Comment by tgamblin** [comment]
@alalazo: trying it now.

**Comment by tgamblin** [comment]
@alalazo I built 5.2.0 and 5.3.0 with this and it worked.  I will merge it in.

**Comment by zhaiyuqiang** [comment]
```
/xxxx/binutils/bin/ld: this linker was not configured to use sysroots
```
I renamed '/xxxx/binutils/bin/ld' to '/xxxx/binutils/bin/ld.bak',  in order that '/usr/bin/ld' was used. 
It works for me.
