### ISSUE TITLE
Detect presence of `~/user-config.jam` for Boost package

### ISSUE THREAD

**Issue by eschnett** [scalability-llnl/spack#185]
Boost cannot be configured with per-directory options; one has to create a (global) `~/user-config.jam`. Thus such files may be present unintentionally. Spack should detect and handle this, either by warning the user, or by renaming (and later restoring) this file.

**Comment by scheibelp** [comment]
Hi Erik I currently have a branch to address this (and a few other issues with building boost packages) at: https://github.com/scheibelp/spack/tree/features/boostfixes

Boost.Build will use the environment variable BOOST_BUILD_PATH to search for user-config.jam, so in this branch the strategy is to place it in the boost source directory (which should avoid this issue).

I'm currently on the fence about whether to pack a few more things into this branch so it may take another couple weeks (although if you have a desire to see it sooner I should be able to speed it up)

**Comment by eschnett** [comment]
Thanks. Now that I know what the issue is, I manually renamed the '~/user-config.jam` file, and I'm fine for the moment.

**Comment by tgamblin** [comment]
We can close this once Peter's PR is merged. Thanks Peter!

**Comment by scheibelp** [comment]
The PR https://github.com/scalability-llnl/spack/pull/214 from @netvvorms (which has been merged) should address this.

**Comment by tgamblin** [comment]
Closing.  @eschnett: lemme know if this is ok
