### ISSUE TITLE
provide more informative error message when package.py execs non-existent binary

### ISSUE THREAD

**Issue by malcook** [scalability-llnl/spack#30]
For instance, building bcftools is simply untar and make;  there is no ./configure file in the tarball.

But the spackage developer (erhm, that is me) failed to remove the default 
```
    configure("--prefix=%s" % prefix)
```  
As a result,
```
spack install bcftools
```
fails with
```
==> Building bcftools.
Traceback (most recent call last):
  File "/n/local/sc/lib/spack/spack/build_environment.py", line 268, in fork
    function()
  File "/n/local/sc/lib/spack/spack/package.py", line 833, in real_work
    self.install(self.spec, self.prefix)
  File "/n/local/sc/var/spack/packages/bcftools/package.py", line 40, in install
    configure("--prefix=%s" % prefix)
  File "/n/local/sc/lib/spack/spack/util/executable.py", line 77, in __call__
    stdout=subprocess.PIPE if return_output else sys.stdout)
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Certainly 'No such file or directory' tells me something is missing.  Shouldn't it be more informative and tell me __WHAT__ is missing?

**Comment by tgamblin** [comment]
This is fixed in the current develop branch and will be in the next release.  Here is a sample of the new error output, which prints code context:

    ==> Already staged libelf in /Users/gamblin2/src/spack/foo.
    ==> No patches needed for libelf.
    ==> Building libelf.
    ==> Error: ./configure: No such file or directory
        Command: ./configure --prefix=/Users/gamblin2/src/spack/opt/macosx_10.9_x86_64/gcc@4.8.3/libelf@foo --enable-shared --disable-dependency-tracking --disable-debug
    ---
    Context:
      /Users/gamblin2/src/spack/var/spack/packages/libelf/package.py:43, in install:
         39       def install(self, spec, prefix):
         40           configure("--prefix=" + prefix,
         41                     "--enable-shared",
         42                     "--disable-dependency-tracking",
      >> 43                     "--disable-debug")
         44           make()
         45   
         46           # The mkdir commands in libelf's install can fail in parallel
         47           make("install", parallel=False)

**Comment by malcook** [comment]
nice!
