### ISSUE TITLE
bug: unique archive directory resulting from untar not detected when there are hidden files from aside

### ISSUE THREAD

**Issue by fpruvost** [scalability-llnl/spack#48]
I have a very specific problem trying to install a package on Linux.

I want to install magma from ICL http://icl.cs.utk.edu/magma/software/index.html
but it seems that the build is not done in the good directory.
Generally, when we untar a tarball, say magma-1.6.2.tar.gz, the resulting directory magma-1.6.2/ is at the same level, but in my case a folder named spack-expanded-archive/ is created and the build is done in it where the source code is actually in a lower stage in spack-expanded-archive/magma-1.6.2/.
Of course there is no Makefile in spack-expanded-archive/ but it is in spack-expanded-archive/magma-1.6.2/.

As Todd has explained, the algorithm in Spack when untaring before building is the following:

1. download the tarball.  Stage directory looks like this:
archive.tar.gz

2. make a spack-expanded-archive directory
archive.tar.gz	
spack-expanded-archive/

3.  expand the archive in the new directory
archive.tar.gz
spack-expanded-archive/
archive/

4. If only ONE directory is created, move that to the top level like this, and remove the temp directory:
archive.tar.gz
archive/

5. If there is more than one file created, or if the created file is not a directory, Spack just leaves the temp directory:
archive.tar.gz
 	spack-expanded-archive/
Makefile
src/
etc...

In my case, the result of 
tar xf http://icl.cs.utk.edu/projectsfiles/magma/downloads/magma-1.6.2.tar.gz
is a hidden file ._magma-1.6.2* and the expected directory magma-1.6.2/
so that we are not in step 4 of the algorithm anymore and Spack try to build in spack-expanded-archive/ where there is no Makefile file of course.

Maybe hidden files should be ignored when the algorithm choose whether or not it faces a crappy tarball.

**Comment by tgamblin** [comment]
Florent: see if the fix I just committed works.  If it does, then I'll merge this into develop

**Comment by tgamblin** [comment]
From Florent:

    Yes it fixes the problem
    Thanks

    Le 01/06/2015 19:26, Todd Gamblin a écrit :
    Florent: see if the fix I just committed works. If it does, then I'll merge this into develop

    —
    Reply to this email directly or view it on GitHub.

merging to develop...
