### ISSUE TITLE
Sourceforge download links unreliable

### ISSUE THREAD

**Issue by trws** [scalability-llnl/spack#59]
A number of packages, I noticed tmux but there are others, have sourceforge links of the form:

```
http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.9/tmux-1.9a.tar.gz
```

These used to work as download links with redirect handling, but now a timestamp appears to be required.  This new form appears to work (on wget from a shell):

```
http://downloads.sourceforge.net/project/tmux/tmux/tmux-1.9/tmux-1.9a.tar.gz?ts=$(date +%s)&use_mirror=autoselect
```

Not sure what the best way to address this is, but a url-handler for sourceforge might be in order.

**Comment by tgamblin** [comment]
@scogland: there are some packages that use other source forge urls -- ones that end in /download.  Did you look at those?  For example, for tmux, you can navigate to here:

    http://sourceforge.net/projects/tmux/files/tmux/tmux-1.9/

And you can copy a link that looks like this:

    http://sourceforge.net/projects/tmux/files/tmux/tmux-1.9/tmux-1.9a.tar.gz/download

I think that URL will work with Spack and is also stable (and doesn't need their URL annotation crap).  Can you see if this fixes things? I am hesitant to include a change for something that tacks weird parameters onto the end of URLs.

I wish there was some crowdsourced place I could go to pay for projects I like to get off of source forge...

**Comment by trws** [comment]
Unfortunately, that's the problem.  That used to work.  Now I get an 
html file named "download" or "download.html" depending on whether you 
use `curl -O` or `wget` respectively.  Does it still work for you?

Using the same URL in a browser or elinks will follow the delayed 
redirect and get the actual file, but I don't know a way to get one of 
the basic download programs to handle it.  I have some python code 
somewhere for invoking an external V8 javascript interpreter to follow 
this kind of redirect, but that's a lot heavier and a lot more 
invasive...

**Comment by trws** [comment]
Closing, this is a configuration issue that needs a completely different solution.  For anyone that finds this by searching, check to make sure your `~/.curlrc` is *not* setting the user agent, it causes sourceforge to indirect out the direct-download link and inject adds.
