### ISSUE TITLE
develop: default behaviour with variants

### ISSUE THREAD

**Issue by fpruvost** [scalability-llnl/spack#77]
Hi,

lets say I have a variant "var" in a package "pac":

    variant('var', default=False, description='Enable lib2 instead of lib1')

and optional dependencies like this:

    depends_on("lib1", when='~var')
    depends_on("lib2", when='+var')

what I expect writting this is to have by default a dependency to lib1 and if variant var is enabled then I depend on lib2 and no more on lib1.

so that when I invoke:

    $ spack install pac

then I depend on lib1, because var is not activated. And If I invoke:

    $ spack install pac+var

then I depend on lib2 and not on lib1

The problem is that for now, with this configuration, if I invoke:

    $ spack install pac

Spack does not detect the dependency to lib1. To get the correct behaviour, I have to write:

    $ spack install pac~var

even if "install pac" implicitly means "install pac~var".

Is it possible to get dependencies resolved with:

    depends_on("lib1", when='~var')

without explicitly add the "~var" in the specs?

Thanks,
Florent

**Comment by tgamblin** [comment]
@fpruvost: I've almost got a fix for this.  There are bugs in the way optional deps are handled initially in concretization.

**Comment by tgamblin** [comment]
@fpruvost: I just pushed a branch called `bugfix/optional-dep-fix`.  Can you see if that fixes this issue in your case?  This branch adds new logic in concretize, and a test case to ensure it'll stay fixed.

**Comment by fpruvost** [comment]
@tgamblin: Yes it fixes this issue and works well! Thanks

The "Normalized" step does not see the deps but the "Concretized" one is correct

    $ spack spec chameleon
    Input spec
    ------------------------------
      chameleon
    
     Normalized
     ------------------------------
       chameleon
     
     Concretized
    ------------------------------
      chameleon@0.9.1%gcc@4.9.2~cuda~fxt~magma~mkl~mpi~quark~simu=unknown_arch
          ^cblas@2015-06-06%gcc@4.9.2=unknown_arch
              ^netlib-blas@3.5.0%gcc@4.9.2=unknown_arch
          ^lapack@3.5.0%gcc@4.9.2+lapacke=unknown_arch
          ^starpu@1.2.0rc2%gcc@4.9.2~cuda~debug~fxt~mpi~opencl~simu=unknown_arch
              ^hwloc@1.11.0%gcc@4.9.2=unknown_arch

**Comment by tgamblin** [comment]
@fpruvost Nice!

The normalized thing is expected -- normalization doesn't actually add any optional dependencies; it fills out as much of the spec as it can without adding constraints.  Adding a default value for a variant counts as adding a constraint and is reserved for concretization. You could have a situation where some other constraint implies a different value for the variant, and setting it to the default at normalize time would preempt that and cause a conflict.

Currently concretization is done greedily, so there still might be issues there with the decision order... at some point concretization probably needs to be replaced by a better constraint search algorithm but greedy seems to work for now.

**Comment by tgamblin** [comment]
I'll put this in develop and close the issue.
