### ISSUE TITLE
How to use shell integration (setup-env.sh)

### ISSUE THREAD

**Issue by justintoo** [scalability-llnl/spack#9]
I'm trying to actually use my installed tools now by sourcing them with the `setup-env.sh` file, but I keep getting the message below:

```bash
aztec2@too1:echo $SHELL
/bin/bash

aztec2@too1:. share/spack/setup-env.sh

aztec2@too1:./bin/spack use rose
==> This command requires spack's shell integration.
  
  To initialize spack's shell commands, you must run one of
  the commands below.  Choose the right command for your shell.
  
  For bash and zsh:
      . /g/g12/too1/development/opt/spack/share/spack/setup-env.sh
  
  For csh and tcsh:
      setenv SPACK_ROOT /g/g12/too1/development/opt/spack
      source /g/g12/too1/development/opt/spack/share/spack/setup-env.csh
```

**Comment by tgamblin** [comment]
How'd you source it?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by justintoo** [comment]
I tried both of these commands from the root of Spack:

```bash
$ . share/spack/setup-env.sh
```

```bash
$ source share/spack/setup-env.sh
```

**Comment by tgamblin** [comment]
I believe you need to first init either modules or dotkit. The message should say that though. What happens when you just type, say, "use git"?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by justintoo** [comment]
```bash
$ use git
Prepending: git (ok)
```

How do I initialize modules / dotkit?

**Comment by tgamblin** [comment]
Looks like dotkit is already inited. Sourcing setup-env.sh should make "spack use ..." work. What she'll do you use?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by justintoo** [comment]
`bash`

**Comment by tgamblin** [comment]
Point me at your spack directory on aztec, and I can try this as you to see
what's up.

From:  Justin Too <notifications@github.com>
Reply-To:  scalability-llnl/spack
<reply+000493429d2e144310becf52994914cf2236118017aaf34e92cf0000000110c54c5e9
2a169ce0332e31a@reply.github.com>
Date:  Wednesday, January 7, 2015 at 2:34 PM
To:  scalability-llnl/spack <spack@noreply.github.com>
Cc:  Todd Gamblin <tgamblin@llnl.gov>
Subject:  Re: [spack] How to use shell integration (setup-env.sh) (#9)

**Comment by justintoo** [comment]
`/g/g12/too1/development/opt/spack`

**Comment by tgamblin** [comment]
As you on aztec, this works for me:

aztec1@too1:use git



This command is part of Dotkit, which you may access

after initializing via the following command:



For csh/tcsh shells:

  source /usr/local/tools/dotkit/init.csh



For sh/ksh/bash shells:

  . /usr/local/tools/dotkit/init.sh



aztec1@too1:. /usr/local/tools/dotkit/init.sh

aztec1@too1:. share/spack/setup-env.sh

aztec1@too1:spack use rose

Prepending: rose@master%gcc@4.8.1-533d9248 (ok)


It looks like you had already sourced the dotkit init.sh but I am not sure
why then sourcing spack's setup-env.sh didn't work for you.

-Todd


From:  Justin Too <notifications@github.com>
Reply-To:  scalability-llnl/spack
<reply+00049342aa94b373cf8f5d2c6d72d226e05618faf8c8be3792cf0000000110c550ec9
2a169ce0332e31a@reply.github.com>
Date:  Wednesday, January 7, 2015 at 2:54 PM
To:  scalability-llnl/spack <spack@noreply.github.com>
Cc:  Todd Gamblin <tgamblin@llnl.gov>
Subject:  Re: [spack] How to use shell integration (setup-env.sh) (#9)

**Comment by justintoo** [comment]
Hmm... Still doesn't work for me. Any other ideas other than trying to debug Spack? (Maybe you're setting extra environment variables/settings that I am not somehow?)

**Comment by tgamblin** [comment]
I did it *as* you with your default environment, so it should work. I've never seen LC's xsu tool not give me a proper env for a user.

Can you log out, log back into aztec, type the commands I did in the previous message, then paste the output?



Sent with Good (www.good.com)


-----Original Message-----

**Comment by justintoo** [comment]
It worked! (I guess just one of those bizarre software things -__- Thanks)

**Comment by tgamblin** [comment]
I think I know what's up. You typed "./bin/spack" but I typed "spack". The shell support uses a "spack" function/alias and that won't work if you use a full path.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by justintoo** [comment]
Ah... Makes sense. Now I know :-)
